services:
  catnip-db:
    image: postgres:11.5
    container_name: catnip-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${POSTGRES_PORT:-5432}
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p ${POSTGRES_PORT:-5432}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  catnip-api:
    container_name: catnip-api
    restart: unless-stopped
    build:
      target: ${ENV:-dev}
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api/app:/app/app
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      - ENV=${ENV:-dev}
      - POSTGRES_HOST=catnip-db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - API_PORT=${API_PORT:-8000}
    env_file:
      - ./.env
    depends_on:
      catnip-db:
        condition: service_healthy

volumes:
  pgdata:
